arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint1:
      p: 95000
      d: 1
      i: 1
      i_clamp: 1
    joint2:
      p: 50000
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 5000
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 5000
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 5000
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 2000
      d: 1
      i: 1
      i_clamp: 1

  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.01
    joint1:
      max_velocity: 1.0


# arm_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - joint1
#     - joint2
#     - joint3
#     - joint4
#     - joint5
#     - joint6
#   gains:
#     joint1:
#       p: 30 #약간 진동
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint2:
#       p: 30
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint3:
#       p: 5
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint4:
#       p: 5
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint5:
#       p: 5
#       d: 1
#       i: 1
#       i_clamp: 1
#     joint6:
#       p: 2
#       d: 1
#       i: 1
#       i_clamp: 1